// src/StylesCargas.jsx
export const TG = {
  black: "#000000",
  blue: "#0066cc",
  blueDark: "#004d99",
  blueLight: "#e6f2ff",
  white: "#ffffff",
  bg: "#f8fafc",
  border: "#d1d5db",
  text: "#111827",
  muted: "#6b7280",
  success: "#10b981",
  warning: "#f59e0b",
  danger: "#ef4444",
  info: "#3b82f6",
};

export const styles = {
  header: {
    background: TG.black,
    color: TG.white,
    padding: "20px 24px",
    borderBottom: `4px solid ${TG.blue}`,
  },
  headerLeft: { display: "flex", alignItems: "center", gap: 16 },

  kpiPanel: {
    background: TG.white,
    border: `1px solid ${TG.border}`,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
  },

  kpiBox: {
    background: TG.white,
    border: `1px solid ${TG.border}`,
    borderRadius: 10,
    padding: "12px 16px",
    minWidth: 120,
    textAlign: "left",
    transition: "all 0.2s ease",
  },

  kpiBadge: {
    background: TG.white,
    border: `1px solid ${TG.border}`,
    borderRadius: 10,
    padding: "8px 12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    minWidth: 140,
    transition: "all 0.2s ease",
  },

  btnClear: {
    border: `1px solid ${TG.border}`,
    background: TG.white,
    padding: "8px 12px",
    borderRadius: 8,
    fontWeight: 600,
    cursor: "pointer",
    color: TG.black,
    fontSize: 13,
    transition: "all 0.2s ease",
  },

  toolbar: {
    background: TG.white,
    border: `1px solid ${TG.border}`,
    borderRadius: 12,
    padding: 16,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
    gap: 12,
    flexWrap: "wrap",
  },

  toolbarSticky: {
    background: TG.white,
    border: `1px solid ${TG.border}`,
    borderRadius: 12,
    padding: 16,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
    gap: 12,
    flexWrap: "wrap",
    position: "sticky",
    top: 10,
    zIndex: 20,
  },

  btnSmall: {
    border: `1px solid ${TG.border}`,
    background: TG.white,
    padding: "8px 10px",
    borderRadius: 8,
    fontWeight: 800,
    cursor: "pointer",
    color: TG.black,
    fontSize: 12,
    transition: "all 0.2s ease",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    whiteSpace: "nowrap",
  },

  sheetWrap: {
    background: TG.white,
    border: `1px solid ${TG.border}`,
    borderRadius: 12,
    overflow: "auto",
    maxHeight: "74vh",
    boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
  },

  sheetTable: {
    width: "max-content",
    borderCollapse: "collapse",
    fontSize: 13,
  },

  thStickyLeft: {
    position: "sticky",
    left: 0,
    zIndex: 5,
    background: TG.black,
    color: TG.white,
    padding: 12,
    textAlign: "left",
    borderRight: `1px solid ${TG.border}`,
    top: 0,
    fontWeight: 700,
    fontSize: 13,
  },

  thDay: {
    position: "sticky",
    top: 0,
    zIndex: 4,
    padding: "8px",
    borderLeft: `1px solid ${TG.border}`,
    borderBottom: `1px solid ${TG.border}`,
    textAlign: "center",
    minWidth: 180,
    fontWeight: 600,
  },

  tdStickyLeft: {
    position: "sticky",
    left: 0,
    zIndex: 3,
    borderRight: `1px solid ${TG.border}`,
    borderBottom: `1px solid ${TG.border}`,
    padding: 12,
    minWidth: 300,
    fontWeight: 600,
    verticalAlign: "top",
  },

  tdDay: {
    borderLeft: `1px solid ${TG.border}`,
    borderBottom: `1px solid ${TG.border}`,
    padding: 10,
    verticalAlign: "top",
    minWidth: 180,
    height: 200,
  },

  tdEmpty: {
    padding: 24,
    textAlign: "center",
    color: TG.muted,
    fontSize: 14,
  },

  btnGhost: {
    border: `1px solid ${TG.border}`,
    background: TG.white,
    padding: "8px 12px",
    borderRadius: 8,
    fontWeight: 600,
    cursor: "pointer",
    color: TG.black,
    fontSize: 14,
    transition: "all 0.2s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 36,
    height: 36,
  },

  input: {
    padding: "10px 12px",
    borderRadius: 8,
    border: `1px solid ${TG.border}`,
    outline: "none",
    fontSize: 14,
    width: "100%",
    background: TG.white,
    color: TG.text,
    transition: "border 0.2s ease",
  },

  btnPrimary: {
    background: TG.blue,
    color: TG.white,
    padding: "12px 20px",
    border: "none",
    borderRadius: 8,
    fontWeight: 700,
    cursor: "pointer",
    fontSize: 14,
    transition: "all 0.2s ease",
  },

  btnSecondary: {
    background: TG.blueLight,
    color: TG.blueDark,
    padding: "12px 20px",
    border: `1px solid ${TG.border}`,
    borderRadius: 8,
    fontWeight: 700,
    cursor: "pointer",
    fontSize: 14,
    transition: "all 0.2s ease",
  },

  btnDangerMini: {
    background: "#fee2e2",
    color: "#991b1b",
    padding: "12px 20px",
    border: "none",
    borderRadius: 8,
    fontWeight: 700,
    cursor: "pointer",
    fontSize: 14,
    transition: "all 0.2s ease",
  },

  cellBox: {
    background: "#f9fafb",
    borderRadius: 8,
    padding: 10,
    border: `1px solid ${TG.border}`,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },

  statusBadge: {
    display: "inline-block",
    padding: "4px 8px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
    border: `1px solid ${TG.border}`,
    width: "fit-content",
    marginBottom: 4,
  },

  cellLine: {
    fontSize: 11,
    fontWeight: 600,
    lineHeight: 1.3,
    whiteSpace: "normal",
    wordBreak: "break-word",
    color: TG.text,
  },

  modalOverlayStyle: {
    position: "fixed",
    inset: 0,
    background: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    zIndex: 999,
    backdropFilter: "blur(2px)",
  },

  modalCardStyle: {
    width: "min(1200px, 100%)",
    background: TG.white,
    borderRadius: 16,
    border: `1px solid ${TG.border}`,
    padding: 24,
    maxHeight: "90vh",
    overflow: "auto",
    boxShadow: "0 20px 40px rgba(0,0,0,0.15)",
  },

  modalCardSmall: {
    width: "min(700px, 100%)",
    background: TG.white,
    borderRadius: 16,
    border: `1px solid ${TG.border}`,
    padding: 24,
    maxHeight: "90vh",
    overflow: "auto",
    boxShadow: "0 20px 40px rgba(0,0,0,0.15)",
  },

  blockTitle: {
    fontWeight: 700,
    color: TG.black,
    marginBottom: 12,
    marginTop: 8,
    fontSize: 16,
    paddingBottom: 8,
    borderBottom: `2px solid ${TG.blueLight}`,
  },

  rangeBar: {
    marginTop: 16,
    padding: 16,
    borderRadius: 12,
    border: `1px solid ${TG.border}`,
    background: "#f9fafb",
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "center",
  },

  rangeLabel: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    fontSize: 13,
    fontWeight: 600,
    color: TG.black,
  },
};
